#!/bin/sh

HOSTNAME=`hostname`
NODENAME="${HOSTNAME}-plugin"

QUEUE=plugin
CONCURRENCY=8

case $1 in
  heavy)
    QUEUE=plugin-heavy
    CONCURRENCY=4
    ;;
  light)
    QUEUE=plugin-light
    CONCURRENCY=16
    ;;
esac

celery worker -A minion.backend.plugin_worker \
  --loglevel=INFO \
  --concurrency="${CONCURRENCY}" \
  -Q "${QUEUE}" \
  -n "$NODENAME"

