#!/usr/bin/env python

import json
import sys

from pymongo import MongoClient

# start-scan <plan-name> <configuration>

if __name__ == "__main__":

    plan_path = sys.argv[1]

    mongodb = MongoClient()

    db = mongodb.minion
    plans = db.plans
    scans = db.scans

    #
    # Insert the plan
    #

    with open(sys.argv[1]) as f:
        plan = json.load(f)
        plans.remove({'name': plan['name']})
        plans.insert(plan)
