#!/usr/bin/env python

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import optparse
from minion.backend.app import app, configure_app

if __name__ == "__main__":

   parser = optparse.OptionParser()
   parser.add_option("-d", "--debug", dest="debug", default=False, action="store_true")
   parser.add_option("-r", "--reload", dest="reload", default=False, action="store_true")
   parser.add_option("-a", "--address", default="127.0.0.1")
   parser.add_option("-p", "--port", type="int", default=8383)

   (options, args) = parser.parse_args()

   app = configure_app(app, debug=options.debug)
   app.run(host=options.address, port=options.port, debug=options.debug,
           use_reloader=options.reload, use_evalex=False)
