#!/usr/bin/env python

import glob
import json
import os
import requests
import shlex
import sys
from subprocess import Popen, PIPE

if __name__ == "__main__":

    ROOT_DIR = os.path.dirname(os.path.abspath(os.path.dirname(__file__)))
    PLANS_DIR = os.path.join(ROOT_DIR, 'plans')

    # Import plans
    plans = glob.glob(PLANS_DIR + '/*.plan')
    for plan in plans:
        with open(plan, 'r') as f:
            plan_json = json.load(f)
        resp = requests.post('http://localhost:8383/plans',
            headers={'content-type': 'application/json'},
            data=json.dumps(plan_json),
        )

    # Collect answers about administrator and initial site setup
    if len(sys.argv) < 4:
        email = raw_input("Enter the administrator's Persona email: ")
        name = raw_input("Enter the administrator's name: ")
        answer = raw_input("Do you want to import some test sites into minion? [y/n]")
    else:
        email = sys.argv[1]
        name = sys.argv[2]
        answer = sys.argv[3]

    # Create administrator
    p = Popen(['minion-create-user', email, name, 'administrator'], stdout=PIPE, stderr=PIPE)
    result = p.communicate()
    print result[0].strip()

    # Create groups
    groups = {
        "security": {
            "description": "These applications suffer common vulnerabilities and are used for testing and training purpose.",
            "sites": [
                "http://zero.webappsecurity.com",
                "http://crackme.cenzic.com",
                "http://testasp.vulnweb.com",
                "http://testaspnet.vulnweb.com",
                "http://testfire.net"
            ],
            "plans": ["basic"]
        }
    }


    if answer in ('y', 'Y'):
        for group, detail in groups.iteritems():
            g = { 'name': group,
                  'description': detail['description'],
                  'users': [email]}
            resp = requests.post('http://localhost:8383/groups',
                                 headers={'content-type': 'application/json'},
                                 data=json.dumps(g))

        # Import sites
        for group, detail in groups.iteritems():
            for site in detail['sites']:
                s = {'url': site,
                     'plans': detail['plans'],
                     'groups': [group],
                     'verification': {'enabled': False, 'value': None}}
                resp = requests.post('http://localhost:8383/sites',
                                     headers={'content-type': 'application/json'},
                                     data=json.dumps(s))
