#!/usr/bin/env python

import json
import sys
import requests

if __name__ == "__main__":

    if len(sys.argv) != 4:
        print "usage: minion-create-user <email> <name> <role>"
        sys.exit(1)

    user = { "email": sys.argv[1], "name": sys.argv[2], "role": sys.argv[3] }

    r = requests.post("http://127.0.0.1:8383/users",
                      headers={'Content-Type': 'application/json'},
                      data=json.dumps(user))
    r.raise_for_status()

    j = r.json()
    if not j.get('success'):
        print "failure: " + j.get("reason", "unknown")
        sys.exit(1)
    else:
        print "success: added {email} ({name}) as {role}".format(email=user['email'], name=user['name'], role=user['role'])
        sys.exit(0)
