#!/bin/bash

exec celery beat -S celerybeatmongo.schedulers.MongoScheduler \
  --config=minion.backend.celeryconfig \
  --logfile=/var/log/minion/scanscheduler.log \
  --loglevel=debug \
  --pidfile=/run/minion/celerybeat.pid \
