#!/bin/sh

HOSTNAME=`hostname`
NODENAME="${HOSTNAME}-plugin"

QUEUE=plugin
CONCURRENCY=8

case $1 in
  heavy)
    QUEUE=plugin-heavy
    CONCURRENCY=4
    ;;
  light)
    QUEUE=plugin-light
    CONCURRENCY=16
    ;;
esac

exec celery worker -A minion.backend.tasks \
  --concurrency="${CONCURRENCY}" \
  --config=minion.backend.celeryconfig \
  --logfile=/var/log/minion/plugin-worker.log \
  --loglevel=INFO \
  --maxtasksperchild=1 \
  -Q "${QUEUE}" \
  -n "$NODENAME"

