#!/usr/bin/env python

import json
import sys
import requests

if __name__ == "__main__":

    if len(sys.argv) != 3:
        print "usage: minion-create-user <email> <role>"
        sys.exit(1)

    user = { "email": sys.argv[1], "role": sys.argv[2] }

    r = requests.post("http://127.0.0.1:8383/users",
                      headers={'Content-Type': 'application/json'},
                      data=json.dumps(user))
    r.raise_for_status()

    j = r.json()
    if not j.get('success'):
        print "failure: " + j.get("reason", "unknown")
