#!/usr/bin/env python

from flask.ext.script import Manager, Server
from minion.backend.api import app

manager = Manager(app)
server = Server(use_debugger=False, use_reloader=False, port=8383, host='127.0.0.1')
manager.add_command("runserver", server)

if __name__ == "__main__":
   manager.run()
